# -*- coding: utf-8 -*-
"""calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EJfiBwn0D-5o7ByWkVPJOn4mN9h2aJn5
"""

def add(x, y):
  return x + y

def subtract(x, y):
  return x - y

def multiply(x, y):
  return x * y

def divide(x, y):
  if y == 0:
    return "Can't divide it by zero"
  return x / y

def calculator():
  print("Simple Calculator")

  while True:
    print("\nSelect Operation from the below list: ")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")
    print("5. Exit")

    choice = input("Enter your choice(1/2/3/4/5): ")

    if choice == '5':
      print("Exiting the Calculator.")
      break

    if choice in ['1', '2', '3', '4']:
      num1 = float(input("Enter first number: "))
      num2 = float(input("Enter second number: "))

      if choice == '1':
        print(f"Result of two numbers : {num1} + {num2} = {add(num1, num2)}")
      elif choice == '2':
        print(f"Result of two numbers : {num1} - {num2} = {subtract(num1, num2)}")
      elif choice == '3':
        print(f"Result of two numbers : {num1} * {num2} = {multiply(num1, num2)}")
      elif choice == '4':
        print(f"Result of two numbers : {num1} / {num2} = {divide(num1, num2)}")
    else:
      print("Invalid choice! Please select a valid operation.")
      continue

calculator()